routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['reset' => false, 'verify' => false, 'register' => false]);

## AUTHENTICATED USER ##
Route::middleware(['auth', 'IsAdmin'])->group(function () {
    Route::group(['namespace' => 'Manages'], function () { 


		Route::get('/', Homes\HomeController::class . '@index')->name('home');

    	Route::resource('user', Users\UserController::class);
    	Route::resource('listing', Listings\ListingController::class);

        
    });
});

app/Models/Listing.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Malhal\Geographical\Geographical;

class Listing extends Model
{

    Use Geographical;
    protected static $kilometers = true;


    protected $fillable = [
        'list_name', 'address', 'latitude', 'longitude', 'submitter_id'
    ];

    public function user () {
        return $this->belongsTo(User::class, 'submitter_id');
    }
}

app/Http/Controllers/API/v1/Listings/ApiListingController.php
<?php

namespace App\Http\Controllers\API\v1\Listings;

use App\Http\Controllers\Controller;
use App\Http\Resources\ListingResource;
use App\Models\Listing;
use App\Supports\ApiSettings;
use Illuminate\Http\Request;
use Validator;

class ApiListingController extends Controller
{
    use ApiSettings;

    public function index(Request $request) { 

    	$data = $this->data;

    	$rules = [
            'latitude'            => 'required|numeric',
            'longitude'           => 'required|numeric',
        ];

        $message = [];

        $validator = Validator::make($request->input(), $rules, $message);

        if ($validator->fails()) {
            return $this->failedResponse($request, $validator->errors()->first());
        }

    	$listings = Listing::distance($request->input('latitude'), $request->input('longitude'))->get();

		array_push($data, $listings);
		$appData = $this->prepareAppData($request, $data);

        return ListingResource::collection($listings)->additional(['AppData' => $appData]);

	}
}

app/Http/Controllers/Manages/Listings/ListingController.php
<?php

namespace App\Http\Controllers\Manages\Listings;

use App\Http\Controllers\Controller;
use App\Models\Listing;
use Illuminate\Http\Request;

class ListingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $lists = Listing::get();


        return view('listings.index', compact('lists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('listings.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            $rules = [
                'name'       => 'required|max:200',
                'address'    => 'required',
                'latitude'   => 'required|numeric',
                'longitude'  => 'required|numeric',
            ];

            $message = [];
            
            $this->validate($request, $rules, $message);

            $user = Listing::create([
                'submitter_id'  => \Auth::user()->id,
                'list_name'     => $request->input('name'),
                'address'       => $request->input('address'),
                'latitude'      => $request->input('latitude'),
                'longitude'     => $request->input('longitude'),
            ]);


        } catch (ValidationException $e) {
            return redirect(route('listing.create'))
                ->withErrors($e->getErrors())
                ->withInput();
        }
        return redirect(route('listing.index'))
            ->withSuccess('New record successfulyy add.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(!$list = Listing::find($id)){
            return back()->withErrors('Record not found');
        }

        return view('listings.show', compact('list'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!$list = Listing::find($id)){
            return back()->withErrors('Record not found');
        }

        return view('listings.edit', compact('list'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {

            $rules = [
                'name'       => 'required|max:200',
                'address'    => 'required',
                'latitude'   => 'required|numeric',
                'longitude'  => 'required|numeric',
            ];

            $message = [];
            
            $this->validate($request, $rules, $message);
       
            if(!$list = Listing::find($id)){
                return back()->withErrors('Record not found');
            }

            $list->update([
                'list_name'     => $request->input('name'),
                'address'       => $request->input('address'),
                'latitude'      => $request->input('latitude'),
                'longitude'     => $request->input('longitude'),
            ]);


        } catch (ValidationException $e) {
            return redirect(route('listing.edit', [$id]))
                ->withErrors($e->getErrors())
                ->withInput();
        }
        return redirect(route('listing.index'))
            ->withSuccess('Record successfulyy update.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

        if ($request->ajax()) {
           if($list = Listing::find($id)){
                $list->delete();
                return response()->json(['status' => 'ok']);
            }
        }
        return Response::json(['status' => 'fail']);
   
    }
}

resources/views/listings/create.blade.php
@extends('components.paper-dashboard.main')

@section('main')
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-content">
                <form action="{{ route('listing.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf      
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-semibold">Name</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}" autocomplete="off" autofocus="" required="" placeholder="e.g. Starbucks @ Mid Valley">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label class="text-semibold">Address</label>
                                <textarea class="form-control" name="address">{{ old('address') }}</textarea>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-semibold">Latitude</label>
                                <input type="text" class="form-control" name="latitude" autocomplete="off" autofocus="" required="" placeholder="e.g. 3.117880" value="{{ old('latitude') }}">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label class="text-semibold">Longitude</label>
                                <input type="text" class="form-control" name="longitude" autocomplete="off" autofocus="" required="" placeholder="e.g. 101.676749" value="{{ old('longitude') }}">
                            </div>
                        </div>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('listing.index') }}" class="btn btn success btn-fill">
                            Back
                        </a>
                        <button type="submit" class="btn btn-success btn-fill">Submit <i class="icon-circle-right2"></i></button>

                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">

</script>
@endsection

resources/views/listings/edit.blade.php
@extends('components.paper-dashboard.main')

@section('main')
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-content">
                <form action="{{ route('listing.update', [$list->id]) }}" method="POST" enctype="multipart/form-data">
                    @csrf      
                    @method('put')      
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-semibold">Name</label>
                                <input type="text" class="form-control" name="name" value="{{ $list->list_name }}" autocomplete="off" autofocus="" required="" placeholder="e.g. Starbucks @ Mid Valley">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label class="text-semibold">Address</label>
                                <textarea class="form-control" name="address">{{ $list->address }}</textarea>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-semibold">Latitude</label>
                                <input type="text" class="form-control" name="latitude" autocomplete="off" autofocus="" required="" placeholder="e.g. 3.117880" value="{{ $list->latitude }}">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label class="text-semibold">Longitude</label>
                                <input type="text" class="form-control" name="longitude" autocomplete="off" autofocus="" required="" placeholder="e.g. 101.676749" value="{{ $list->longitude }}">
                            </div>
                        </div>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('listing.index') }}" class="btn btn success btn-fill">
                            Back
                        </a>
                        <button type="submit" class="btn btn-success btn-fill">Submit <i class="icon-circle-right2"></i></button>

                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">

</script>
@endsection

resources/views/listings/index.blade.php
@extends('components.paper-dashboard.main')

@section('main')
<div class="row">

    <div class="col-md-12">
        <div class="card">
            <div class="card-content">
                <div class="toolbar">
                    <!--Here you can write extra buttons/actions for the toolbar-->
                </div>
                <div class="col-lg-12" style="padding-bottom: 50px !important;">
                    <a href="{{ route('listing.create') }}">
                        <button class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add New</button>
                    </a>
                </div>
                <div class="fresh-datatables">
                    <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Location</th>
                                <th>Submit By</th>
                                <th>Created At</th>
                                <th style="text-align: center;">Action</th>
                            </tr>
                        </thead>
                        <tbody>

                          @foreach($lists as $list)
                            <tr>
                              <td>{{ $list->list_name }}</td>
                              <td>{{ $list->address }}</td>
                              <td>{{ $list->latitude . ' , ' .  $list->longitude }}</td>
                              <td>{{ $list->user->name }}</td>
                              <td>{{ $list->created_at->toDateTimeString() }}</td>
                              <td>
                                <a href="{{ route('listing.edit', [$list->id]) }}" class="btn btn-primary btn-fill btn-sm">Edit</a>
                                <a href="{{ route('listing.show', [$list->id]) }}" class="btn btn-default btn-fill btn-sm">Show</a>
                                <a href="{{ route('listing.destroy', [$list->id]) }}" class="btn btn-danger btn-sm btn-fill ajaxDeleteButton">Delete</a>
                              </td>
                            </tr>
                          @endforeach
                       
                       </tbody>
                    </table>
                </div>


            </div>
        </div><!--  end card  -->
    </div> <!-- end col-md-12 -->
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {

        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            responsive: true,
            language: {
            search: "_INPUT_",
                searchPlaceholder: "Search records",
            }
        });

    });
</script>
@endsection

resources/views/listings/show.blade.php
@extends('components.paper-dashboard.main')

@section('main')
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="text-semibold">Name</label>
                            <input type="text" class="form-control" name="name" value="{{ $list->list_name }}" autocomplete="off" autofocus="" required="" placeholder="e.g. Starbucks @ Mid Valley" readonly="">
                        </div>
                    </div>
                    <div class="col-md-6">

                        <div class="form-group">
                            <label class="text-semibold">Address</label>
                            <textarea class="form-control" name="address" readonly="">{{ $list->address }}</textarea>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="text-semibold">Latitude</label>
                            <input type="text" class="form-control" name="latitude" autocomplete="off" autofocus="" required="" placeholder="e.g. 3.117880" value="{{ $list->latitude }}" readonly="">
                        </div>
                    </div>
                    <div class="col-md-6">

                        <div class="form-group">
                            <label class="text-semibold">Longitude</label>
                            <input type="text" class="form-control" name="longitude" autocomplete="off" autofocus="" required="" placeholder="e.g. 101.676749" value="{{ $list->longitude }}" readonly="">
                        </div>
                    </div>
                </div>
                <div class="pull-right">
                    <a href="{{ route('listing.index') }}" class="btn btn success btn-fill">
                        Back
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">

</script>
@endsection