routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['reset' => false, 'verify' => false, 'register' => false]);

## AUTHENTICATED USER ##
Route::middleware(['auth', 'IsAdmin'])->group(function () {
    Route::group(['namespace' => 'Manages'], function () { 


		Route::get('/', Homes\HomeController::class . '@index')->name('home');

    	Route::resource('user', Users\UserController::class);
    	Route::resource('listing', Listings\ListingController::class);

        
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Manages/Users/UserController.php
<?php

namespace App\Http\Controllers\Manages\Users;

use Response;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::where('type', 'u')->get();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            $rules = [
                'name'       => 'required|max:200',
                'email'      => 'required|email|unique:users',
                'password'      => 'required|string|min:6|confirmed',
            ];

            $message = [];
            
            $this->validate($request, $rules, $message);

            $user = User::create([
                'name'      => $request->input('name'),
                'email'     => $request->input('email'),
                'password'  => bcrypt($request->input('password')),
            ]);


        } catch (ValidationException $e) {
            return redirect(route('user.create'))
                ->withErrors($e->getErrors())
                ->withInput();
        }
        return redirect(route('user.index'))
            ->withSuccess('New record successfulyy add.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(!$user = User::where('id', $id)->where('type', 'u')->first()){
            return back()->withErrors('Record not found');
        }

        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!$user = User::where('id', $id)->where('type', 'u')->first()){
            return back()->withErrors('Record not found');
        }

        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {

            $rules = [
                'name'       => 'required|max:200',
            ];

            $message = [];
            
            $this->validate($request, $rules, $message);
       
            if(!$user = User::where('id', $id)->where('type', 'u')->first()){
                return back()->withErrors('Record not found');
            }            

            $user->update([
                'name'      => $request->input('name'),
            ]);


        } catch (ValidationException $e) {
            return redirect(route('user.edit', [$id]))
                ->withErrors($e->getErrors())
                ->withInput();
        }
        return redirect(route('user.index'))
            ->withSuccess('Record successfulyy updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

        if ($request->ajax()) {
           if($user = User::where('id', $id)->where('type', 'u')->first()){
                $user->delete();
                return response()->json(['status' => 'ok']);
                
            }
        }
        return Response::json(['status' => 'fail']);

    }
}

resources/views/users/create.blade.php
@extends('components.paper-dashboard.main')

@section('main')
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-content">
                <form action="{{ route('user.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf      
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-semibold">Email</label>
                                <input type="email" class="form-control" name="email" value="{{ old('email') }}" autocomplete="off" autofocus="" required="" placeholder="e.g. email@example.com">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label class="text-semibold">Name</label>
                                <input type="text" class="form-control" name="name" autocomplete="off" required="" placeholder="e.g. Carol Pearson" value="{{ old('name') }}">
                            </div>
                        </div>

                        <div class="col-md-6">


                            <div class="form-group">
                                <label class="text-semibold">Password</label>
                                <input type="password" class="form-control" name="password" autocomplete="off" autofocus="" required="" placeholder="e.g. password123" value="">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label class="text-semibold">Password</label>
                                <input type="password" class="form-control" name="password_confirmation" autocomplete="off" autofocus="" required="" placeholder="e.g. password123" value="">
                            </div>
                        </div>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('user.index') }}" class="btn btn success btn-fill">
                            Back
                        </a>
                        <button type="submit" class="btn btn-success btn-fill">Submit <i class="icon-circle-right2"></i></button>

                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">

</script>
@endsection

resources/views/users/edit.blade.php
@extends('components.paper-dashboard.main')

@section('main')
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-content">
                <form action="{{ route('user.update', [$user->id]) }}" method="POST" enctype="multipart/form-data">
                    @csrf      
                    @method('put')      
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-semibold">Email</label>
                                <input type="email" class="form-control" value="{{ $user->email }}" autocomplete="off" autofocus="" required="" placeholder="e.g. email@example.com" readonly="">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label class="text-semibold">Name</label>
                                <input type="text" class="form-control" name="name" autocomplete="off" required="" placeholder="e.g. Carol Pearson" value="{{ $user->name }}">
                            </div>
                        </div>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('user.index') }}" class="btn btn success btn-fill">
                            Back
                        </a>
                        <button type="submit" class="btn btn-success btn-fill">Submit <i class="icon-circle-right2"></i></button>

                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">

</script>
@endsection

resources/views/users/index.blade.php
@extends('components.paper-dashboard.main')

@section('main')
<div class="row">

    <div class="col-md-12">
        <div class="card">
            <div class="card-content">
                <div class="toolbar">
                    <!--Here you can write extra buttons/actions for the toolbar-->
                </div>
                <div class="col-lg-12" style="padding-bottom: 50px !important;">
                    <a href="{{ route('user.create') }}">
                        <button class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add New</button>
                    </a>
                </div>
                <div class="fresh-datatables">
                    <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Created At</th>
                                <th style="text-align: center;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                       		
                       		@foreach($users as $user)
                       			<tr>
                       				<td>{{ $user->name }}</td>
                       				<td>{{ $user->email }}</td>
                       				<td>{{ $user->created_at->toDateTimeString() }}</td>
                       				<td>
                       					<a href="{{ route('user.edit', [$user->id]) }}" class="btn btn-primary btn-fill btn-sm">Edit</a>
                       					<a href="{{ route('user.show', [$user->id]) }}" class="btn btn-default btn-fill btn-sm">Show</a>
                       					<a href="{{ route('user.destroy', [$user->id]) }}" class="btn btn-danger btn-sm btn-fill ajaxDeleteButton">
								                  Delete
								                </a>
                       				</td>
                       			</tr>
                       		@endforeach
                       </tbody>
                    </table>
                </div>


            </div>
        </div><!--  end card  -->
    </div> <!-- end col-md-12 -->
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {

        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            responsive: true,
            language: {
            search: "_INPUT_",
                searchPlaceholder: "Search records",
            }
        });
    });
</script>
@endsection

resources/views/users/show.blade.php
@extends('components.paper-dashboard.main')

@section('main')
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="text-semibold">Email</label>
                            <input type="email" class="form-control" value="{{ $user->email }}" autocomplete="off" autofocus="" required="" placeholder="e.g. email@example.com" readonly="">
                        </div>
                    </div>
                    <div class="col-md-6">

                        <div class="form-group">
                            <label class="text-semibold">Name</label>
                            <input type="text" class="form-control" name="name" autocomplete="off" required="" placeholder="e.g. Carol Pearson" value="{{ $user->name }}" readonly="">
                        </div>
                    </div>
                </div>
                <div class="pull-right">
                    <a href="{{ route('user.index') }}" class="btn btn success btn-fill">
                        Back
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">

</script>
@endsection